[package]
name = "rp2gen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
anyhow = { workspace = true }
csv = { workspace = true }
clap = { workspace = true }
dt-plugin-kraken = { workspace = true }
