[package]
name = "dt-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
toml = { workspace = true }
nom = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
